import Organization from './Organization';
import Media from './Media';
import Implementation from './Implementation';
import Tag from './Tag';
import Faq from './Faq';
import FundFormula from '../../../webshop/props/models/FundFormula';
import FundCriterion from './FundCriterion';
import PhysicalCardType from './PhysicalCardType';

interface FundVoucherStatistics {
    active_vouchers_amount?: string;
    active_vouchers_amount_locale?: string;
    vouchers_amount?: string;
    vouchers_amount_locale?: string;
    inactive_vouchers_amount?: string;
    inactive_vouchers_amount_locale?: string;
    deactivated_vouchers_amount?: string;
    deactivated_vouchers_amount_locale?: string;
    vouchers_count?: number;
    active_vouchers_count?: number;
    inactive_vouchers_count?: number;
    deactivated_vouchers_count?: number;
    children_count?: number;
}

export interface InlineFundPhysicalCardType {
    id: number;
    fund_id: number;
    physical_card_type_id: number;
    allow_physical_card_linking: boolean;
    allow_physical_card_requests: boolean;
    allow_physical_card_deactivation: boolean;
    physical_card_type: PhysicalCardType;
}

export default interface Fund {
    id: number;
    key?: string;
    name?: string;
    logo?: Media;
    description?: string;
    description_html: string;
    description_short?: string;
    how_it_works?: string;
    how_it_works_html?: string;
    organization_id: number;
    organization?: Organization;
    products_count_all?: number;
    products_count_approved?: number;
    products_count_available?: number;
    state?: 'pending' | 'active' | 'closed' | 'paused' | 'waiting';
    state_locale?: string;
    start_date?: string;
    start_date_locale?: string;
    end_date?: string;
    end_date_locale?: string;
    fund_amount?: string;
    fund_amount_locale?: string;
    external?: boolean;
    show_subsidies?: boolean;
    show_qr_limits?: boolean;
    show_qr_code?: boolean;
    show_requester_limits?: boolean;
    allow_direct_payments?: boolean;
    fund_form_id?: number;
    archived?: boolean;
    expired?: boolean;
    request_btn_text?: string;
    external_link_url?: string;
    external_link_text?: string;
    description_position?: 'before' | 'after' | 'replace';
    implementation?: Implementation;
    allow_voucher_records?: boolean;
    allow_voucher_top_ups?: boolean;
    limit_per_voucher?: string;
    limit_per_voucher_locale?: string;
    limit_sum_vouchers?: string;
    limit_sum_vouchers_locale?: string;
    limit_voucher_top_up_amount?: string;
    limit_voucher_total_amount?: string;
    type_locale?: string;
    url_webshop?: string;
    backoffice?: {
        backoffice_enabled?: boolean;
        backoffice_url?: string;
        backoffice_key?: string;
        backoffice_certificate?: string;
        backoffice_fallback?: boolean;
        backoffice_ineligible_policy?: string;
        backoffice_ineligible_redirect_url?: string;
    };
    requester_count: number;
    criteria?: Array<FundCriterion>;
    criteria_editable: boolean;
    provider_organizations_count: number;
    provider_employees_count: number;
    is_configured: boolean;
    sponsor_count: number;
    auth_2fa_policy?: 'global' | 'optional' | 'required' | 'restrict_features';
    auth_2fa_remember_ip?: boolean;
    auth_2fa_restrict_emails?: boolean;
    auth_2fa_restrict_auth_sessions?: boolean;
    auth_2fa_restrict_bi_connections?: boolean;
    auth_2fa_restrict_reimbursements?: boolean;
    organization_funds_2fa?: {
        auth_2fa_policy: 'global' | 'optional' | 'required' | 'restrict_features';
        auth_2fa_remember_ip?: boolean;
        auth_2fa_restrict_emails?: boolean;
        auth_2fa_restrict_auth_sessions?: boolean;
        auth_2fa_restrict_reimbursements?: boolean;
        auth_2fa_restrict_bi_connections?: boolean;
    };
    allow_fund_requests?: boolean;
    allow_fund_request_prefill?: boolean;
    allow_prevalidations?: boolean;
    tags: Array<Tag>;
    faq?: Array<Faq>;
    csv_primary_key: string;
    csv_required_keys: Array<string>;
    csv_required_keys_except_prefill: Array<string>;
    csv_required_keys_by_groups: Array<string>;
    formulas?: Array<FundFormula>;
    budget?: FundVoucherStatistics & {
        used_active_vouchers?: string;
        used_active_vouchers_locale?: string;
        total?: string;
        total_locale?: string;
        used?: string;
        used_locale?: string;
        left?: string;
        left_locale?: string;
        transaction_costs?: string;
        transaction_costs_locale?: string;
    };
    product_vouchers: FundVoucherStatistics;
    payout_vouchers: FundVoucherStatistics;
    faq_title?: string;
    allow_reimbursements?: boolean;
    allow_voucher_payouts?: boolean;
    allow_voucher_payouts_partial?: boolean;
    allow_voucher_payout_count?: number | null;
    allow_physical_cards?: boolean;
    allow_blocking_vouchers?: boolean;
    allow_custom_amounts?: boolean;
    allow_preset_amounts?: boolean;
    allow_custom_amounts_validator?: boolean;
    allow_preset_amounts_validator?: boolean;
    custom_amount_min?: string;
    custom_amount_max?: string;
    amount_presets?: Array<{ id?: number; name?: string; amount?: string; amount_locale?: string }>;
    provider_products_required?: boolean;
    pre_check_excluded?: boolean;
    pre_check_note?: string;
    help_title?: string;
    help_block_text?: string;
    help_button_text?: string;
    help_show_email?: boolean;
    help_show_phone?: boolean;
    help_show_website?: boolean;
    help_show_chat?: boolean;
    help_email?: string;
    help_phone?: string;
    help_website?: string;
    help_chat?: string;
    help_description?: string;
    help_description_html?: string;
    help_enabled?: boolean;
    fund_request_intro?: string;
    fund_request_intro_html?: string;
    allow_provider_sign_up?: boolean;
    outcome_type?: 'voucher' | 'payout';
    fund_request_physical_card_enable?: boolean;
    fund_request_physical_card_type_id?: number;
    fund_physical_card_types?: Array<InlineFundPhysicalCardType>;
    hide_voucher_amount?: boolean;
}
