import Media from './Media';
import Announcement from './Announcement';
import ImplementationPage from './ImplementationPage';
import Language from './Language';
import type { OpenIdFlow } from './OpenIdFlow';

export default interface Implementation {
    id: number;
    name: string;
    key?: string;
    logo?: string;
    organization_id?: number;
    url_provider_terms_page?: string;
    url_webshop?: string;
    has_provider_terms_page: boolean;
    informal_communication?: boolean;
    email_color?: string;
    email_signature?: string;
    email_logo?: Media;
    email_signature_html?: string;
    email_color_default?: string;
    email_signature_default?: string;
    email_logo_default?: Media;
    title?: string;
    description?: string;
    description_html?: string;
    description_alignment?: string;
    email_from_name?: string;
    email_from_address?: string;
    digid_enabled?: boolean;
    digid_available?: boolean;
    openid_enabled?: boolean;
    openid_configured?: boolean;
    openid_available?: boolean;
    openid_flows?: Array<OpenIdFlow>;
    openid_flow_options?: Array<OpenIdFlow>;
    digid_app_id?: string;
    digid_shared_secret?: string;
    digid_a_select_server?: string;
    overlay_type?: string;
    overlay_enabled?: boolean;
    pre_check_url?: string;
    communication_type?: string;
    overlay_opacity?: number;
    banner?: Media;
    pre_check_banner?: Media;
    announcement?: Announcement;
    page_types?: Array<{
        key: string;
        type: 'element' | 'block' | 'extra' | 'static';
        blocks: boolean;
        faq: boolean;
        webshop_url: string;
        description_position_configurable: boolean;
    }>;
    show_home_map?: boolean;
    show_home_products?: boolean;
    show_provider_map?: boolean;
    show_providers_map?: boolean;
    show_office_map?: boolean;
    show_voucher_map?: boolean;
    show_product_map?: boolean;
    pages: Array<ImplementationPage>;
    pre_check_enabled: boolean;
    pre_check_title: string;
    pre_check_description: string;
    pre_check_banner_state: string;
    pre_check_banner_label: string;
    pre_check_banner_description: string;
    pre_check_banner_title: string;
    allow_per_fund_notification_templates?: boolean;
    page_title_suffix?: string;
    show_terms_checkbox?: boolean;
    show_privacy_checkbox?: boolean;
    banner_media_uid?: string;
    languages?: Array<Language>;
    banner_color?: string;
    banner_background?: string;
    banner_background_mobile?: boolean;
    banner_position?: 'left' | 'center' | 'right';
    banner_wide?: boolean;
    banner_collapse?: boolean;
    banner_button?: boolean;
    banner_button_url?: string;
    banner_button_text?: string;
    banner_button_target?: 'self' | '_blank';
    banner_button_type?: 'color' | 'white';
    products_default_sorting?: string;
    auth_page_title?: string;
    auth_page_login_title?: string;
    auth_page_login_email?: boolean;
    auth_page_login_digid?: boolean;
    auth_page_login_openid?: boolean;
    auth_page_login_qr?: boolean;
    auth_page_info_enabled?: boolean;
    auth_page_info_title?: string;
    auth_page_info_description?: string;
    auth_page_info_description_html?: string;
}
