name: Publish Docker Implementation
on: 
  pull_request:
    types: labeled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        IMPLEMENTATION_NAME: "groningen"
      with:
        name: teamforus/forus-frontend-internal
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        buildargs: IMPLEMENTATION_NAME